### ISSUE TITLE
Allow log level definition

### ISSUE THREAD

**Issue by ddinchev** [jdsingh/papertrail-timber#14]
First, thanks for the library! One thing that would be really useful is if you could allow filtering logs based on their level. In production, it's useful to get logs, but not debug and info, but warning+ for example. Would you consider such an improvement?

**Comment by jdsingh** [comment]
Hi @ddinchev 

Thanks for the request.  I have added the `priority` method on the `PapertrailTree.Builder` class where you can specify log priority you're interested in.

New builder looks like this in version 1.0.2.

```kotlin
val tree = PapertrailTree.Builder()
            .system("Android")
            .program("Papertrail")
            .logger("My-App")
            .host(BuildConfig.PAPERTRAIL_HOST)
            .port(BuildConfig.PAPERTRAIL_PORT)
            .priority(Log.INFO)
            .build()
            
Timber.plant(tree)
```

It will send all Info and info+ logs to papertrail.
