### ISSUE TITLE
Be able to log stack traces

### ISSUE THREAD

**Issue by ddinchev** [jdsingh/papertrail-timber#15]
Is there a possibility to log multi-line stack traces for exceptions via `papertrail-timber`? I'm using the library to log unexpected errors but having only the message, rarely provides enough context.

Thank you!

**Comment by jdsingh** [comment]
@ddinchev If you log the exception using `Timber.e(throwable, "Error message")` method then the stacktrace of that throwable object will be passed to papertrail.

It will look something like this.

https://www.dropbox.com/s/4zihi75hxvmiwj5/Screenshot%202018-12-13%2018.02.56.png?dl=0

**Comment by ddinchev** [comment]
I had configured the module in a way that wasn't logging the stack traces properly. Really appreciate your time!
